module.exports = {
  CHATGPT_API_KEY: 'CHATGPT_API_KEY',
  CHATGPT_MODEL: 'CHATGPT_MODEL',
  CHATGPT_PROMPT: 'CHATGPT_PROMPT',
  CHATGPT_TEMPERATURE: 'CHATGPT_TEMPERATURE',
  CHATGPT_MAX_TOKENS: 'CHATGPT_MAX_TOKENS',
  CHATGPT_REASONING_EFFORT: 'CHATGPT_REASONING_EFFORT'
}
